name: CI

on:
  push:
    branches: 
      - '*'
  watch:
    types: [started]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run browser tests
    steps:
    - name: Start Selenoid server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Run tests
      run: mvn clean test -Denv=remote
    - name: Generate Allure Report
      run: mvn allure:report
    - name: Attach Allure Report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./target/site/allure-maven-plugin
